trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'e8300ce3-6cb0-4000-a609-30873c85390f'
  resourceGroupName: 'scloud-poc'
  appName: 'api-vbi-app'
  nodeVersion: '14.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build App'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(appName)'
    package: '$(System.DefaultWorkingDirectory)/build'
    runtimeStack: 'DOTNETCORE|3.1'
    startupCommand: 'npm start'
  displayName: 'Deploy to Azure App Service'