trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '8a332603-e144-4f68-8023-4afd01270469'
  resourceGroupName: 'scloud-poc'
  appName: 'oa-reactapp-test'
  nodeVersion: '14.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build App'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

# - task: DownloadBuildArtifacts@0
#   inputs:
#     buildType: 'current'
#     downloadType: 'single'
#     artifactName: 'react-app'
#     downloadPath: '$(System.ArtifactsDirectory)/react-app'
#   displayName: 'Download Artifact'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '$(azureSubscription)'
#     appType: 'webApp'
#     appName: '$(appName)'
#     package: '$(System.DefaultWorkingDirectory)/react-app/build'
#     runtimeStack: 'DOTNETCORE|3.1'
#     startupCommand: 'npm start'
#   displayName: 'Deploy to Azure App Service'
  