name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'dev'
        options:
          - dev
          - qa

jobs:
  # prepare:
  #   uses: ./.github/workflows/set-matrix.yml
  #   with:
  #     environment: ${{ github.event.inputs.environment }}

  test-vpn:
    runs-on: ubuntu-latest

    steps:
      - name: Install WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard

      - name: Setup WG Config
        run: |
          echo "${{ secrets.WG_CONFIG }}" > wg0.conf
          sudo mv wg0.conf /etc/wireguard/wg0.conf
          sudo chmod 600 /etc/wireguard/wg0.conf

      - name: Connect to VPN
        run: |
          sudo wg-quick up wg0
          sleep 5
          sudo wg

      - name: Test Access to AWS
        run: |
          ping -c 4 192.168.2.1

  # deploy:
  #   needs: prepare
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
  #   steps:
  #     - name: Deploy to ${{ matrix.env }}
  #       run: | 
  #         echo "Deploying to ${{ matrix.env }} with image ${{ matrix.image }}"
  #         echo "Build: ${{matrix.build}}"
      
  # a:
  #   name: a
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "A"
  #     - id: set
  #       run: |
  #         echo "::set-output name=run_job_b::yes"
  #   outputs:
  #     run_job_b: ${{ steps.set.outputs.run_job_b }}  
  # # sonar:
  # #   uses: rperiyasamy/circleci-demo/.github/workflows/sample.yaml@main
  # #   with:
  # #     environment: 'dev'
  # #   env:
  # #     GITHUB_TOKEN: ${{ secrets.PAT }}
  # b:
  #   name: b
  #   runs-on: ubuntu-latest
  #   needs:
  #     - a
  #   if: needs.a.outputs.run_job_b == 'yes'
  #   steps:
  #     - run: |
  #         echo "B"  
  #         # exit 1
  # c:
  #   name: c
  #   runs-on: ubuntu-latest
  #   needs:
  #     - a
  #     - b
  #   if: always() && (needs.b.result == 'success' || needs.b.result == 'skipped')
  #   steps:
  #     - run: echo "C1"
