name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'dev'
        options:
          - dev
          - qa

jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::yes"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}  
  b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'yes'
    steps:
      - run: echo "B"  
  c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - ${{ github.event.inputs.environment != 'dev' || 'b' }}
    if: needs.b.result == 'success' || needs.b.result == 'skipped'
    steps:
      - run: echo "C"
