name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'dev'
        options:
          - dev
          - qa

jobs:
  setup-matrix:
    uses: ./.github/workflows/set-matix.yml
    with:
      environment: ${{ github.event.inputs.environment }}

  deploy:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Deploy to ${{ matrix.env }}
        run: | 
          echo "Deploying to ${{ matrix.env }} with image ${{ matrix.image }}"
          echo "Build: ${{matrix.build}}"
      
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::yes"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}  
  # sonar:
  #   uses: rperiyasamy/circleci-demo/.github/workflows/sample.yaml@main
  #   with:
  #     environment: 'dev'
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.PAT }}
  b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'yes'
    steps:
      - run: |
          echo "B"  
          # exit 1
  c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - b
    if: always() && (needs.b.result == 'success' || needs.b.result == 'skipped')
    steps:
      - run: echo "C1"
