name: Build and deploy API-Automation lambdas

on:
  push:
    branches:
      - 'dev'
#     - 'main'

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'dev'
        options:
          - prod
          - dev
          - nqa
      lambda:
        type: choice
        description: 'Lambda function (Select only if deploying a Lambda function)'
        required: false
        default: 'None'
        options:
          - None
          - patient-create-automation
          - patient-documents-reports
          - hl7parser-automation
          - patient-documentation-automation
          - patient-search
          - patient-insurance-automation
          - patient-upload-document
          - patient-claim-automation
          - patient-multiple-automation

      layer:
        type: choice
        description: 'Lambda Layer (Select only if deploying a Layer)'
        required: false
        default: 'None'
        options:
          - None
          - config_and_error_layer
          - powertool-layer
          - request_oauth_layer

env:
  SERVICE: lambdas
  
permissions:
  contents: read
  id-token: write
  issues: write
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate image tag
        run: |
          echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Set Matrix
        id: set-matrix
        run: |
          {
           # deploy from dev branch to dev
          if [[ ${GITHUB_REF} == 'refs/heads/dev' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
            echo "matrix<<EOF"
            echo "{\"include\":[{\"env\":\"ndev\",\"image\":\"${{env.SHA}}-dev\",\"build\":true}]}"
          elif [[ ${GITHUB_REF} == 'refs/heads/prod' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
            echo "matrix<<EOF"
            echo "{\"include\":[{\"env\":\"dev\",\"image\":\"${{env.SHA}}-prod\",\"build\":true}]}"
          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            echo "matrix<<EOF"
            echo "{\"include\":["
              if [[ "${{ github.event.inputs.environment }}" == 'dev' ]]; then
                echo "{\"env\":\"ndev\",\"image\":\"${{env.SHA}}-dev\",\"build\":true},"
              elif [[ "${{ github.event.inputs.environment }}" == 'prod' ]]; then
                echo "{\"env\":\"dev\",\"image\":\"${{env.SHA}}-prod\",\"build\":false},"
              elif [[ "${{ github.event.inputs.environment }}" == 'nqa' ]]; then
                echo "{\"env\":\"nqa\",\"image\":\"${{env.SHA}}-nqa\",\"build\":false},"
              else
                echo "{\"env\":\"${environment}\",\"image\":\"latest\"},"
              fi
            echo "]}"
          else
            echo "matrix<<EOF"
            echo ""
          fi
          echo EOF
          } >> $GITHUB_OUTPUT
      - name: Echo Matrix
        run: |
          echo "${{ steps.set-matrix.outputs.matrix }}"

  find-modified-lambdas:
    needs: prepare
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    outputs:
      lambdas: ${{ steps.changed.outputs.lambdas }}
      layers: ${{ steps.changed.outputs.layers }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: changed
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE=origin/${{ github.base_ref }}
          else
            BASE=HEAD~1
          fi

          # Get unique first-level folder names from lambda_functions
          LAMBDAS=$(git diff --name-only $BASE HEAD \
            | grep '^root/lambda_functions/' \
            | cut -d/ -f2 \
            | sort -u)

          # Get unique first-level folder names from layers
          LAYERS=$(git diff --name-only $BASE HEAD \
            | grep '^root/layers/' \
            | cut -d/ -f2 \
            | sort -u)

          # Convert to JSON arrays, set to None if empty
          if [ -z "$LAMBDAS" ]; then
            LAMBDAS_JSON="None"
          else
            LAMBDAS_JSON=$(printf '%s\n' $LAMBDAS | jq -R -s -c 'split("\n")[:-1]')
          fi

          if [ -z "$LAYERS" ]; then
            LAYERS_JSON="None"
          else
            LAYERS_JSON=$(printf '%s\n' $LAYERS | jq -R -s -c 'split("\n")[:-1]')
          fi

          echo "Detected lambdas JSON: $LAMBDAS_JSON"
          echo "Detected layers JSON: $LAYERS_JSON"
          echo "lambdas=$LAMBDAS_JSON" >> $GITHUB_OUTPUT
          echo "layers=$LAYERS_JSON" >> $GITHUB_OUTPUT

  approval:
    needs: [prepare]
    runs-on: ubuntu-latest
    if: ${{ needs.prepare.outputs.matrix != '' }}
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    environment: ${{ matrix.env }} 
    steps:
      - name: approve-prod-deployment
        if: ${{ matrix.env == 'prod' }}
        uses: trstringer/manual-approval@v1
        timeout-minutes: 30
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ vars.APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deploying c1-providerservice to ${{ matrix.env }}"

      - name: Approval Received
        if: ${{ matrix.env == 'prod' }}
        run: echo "Approval for deploying c1-providerservice to ${{ matrix.env }} was received"

  build:
    needs:
      - prepare
      - find-modified-lambdas
      - approval
    if: ${{ needs.prepare.outputs.matrix != '' }}
    strategy:
      lambda: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.lambda != 'None' && fromJSON(format('[{0}]', toJSON(github.event.inputs.lambda))) || fromJSON(needs.find-modified-lambdas.outputs.lambdas) }}
      layer: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.layer != 'None' && fromJSON(format('[{0}]', toJSON(github.event.inputs.layer))) || fromJSON(needs.find-modified-lambdas.outputs.layers) }}
      fail-fast: false
    runs-on: ubuntu-latest
    outputs:
      BUILD_PATH: ${{ steps.set-path.outputs.BUILD_PATH }}
      BUILD_TARGET: ${{ steps.set-path.outputs.BUILD_TARGET }}
    environment: ${{ matrix.env }}
    env:
      IMAGE_TAG: ${{ matrix.image }}
      APP_ENV: ${{ matrix.env }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Configure AWS Credentials
      #   id: aws-credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/github-actions-${{ matrix.env }}
      #     role-duration-seconds: 3600
      #     output-credentials: true
      #     aws-region: ${{ vars.AWS_REGION }}

      - name: Determine Build Path
        id: set-path
        run: |
          # For workflow_dispatch
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.lambda }}" != "None" && "${{ github.event.inputs.layer }}" != "None" ]]; then
              echo "Error: You must select either 'lambda' OR 'layer', not both."
              exit 1
            elif [[ "${{ github.event.inputs.lambda }}" != "None" ]]; then
              echo "BUILD_PATH=root/lambda_functions/${{ github.event.inputs.lambda }}" >> $GITHUB_ENV
              echo "BUILD_TARGET=${{ github.event.inputs.lambda }}" >> $GITHUB_ENV
              echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
              echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.inputs.layer }}" != "None" ]]; then
              echo "BUILD_PATH=root/layers/${{ github.event.inputs.layer }}" >> $GITHUB_ENV
              echo "BUILD_TARGET=${{ github.event.inputs.layer }}" >> $GITHUB_ENV
              echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
              echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
            else
              echo "Error: You must select either a 'lambda' or a 'layer' to proceed."
              exit 1
            fi
          # For automated push (detected lambda from matrix)
          else
            echo "BUILD_PATH=root/lambda_functions/${{ matrix.lambda }}" >> $GITHUB_ENV
            echo "BUILD_TARGET=${{ matrix.lambda }}" >> $GITHUB_ENV
            echo "BUILD_PATH=${{ env.BUILD_PATH }}" >> $GITHUB_OUTPUT
            echo "BUILD_TARGET=${{ env.BUILD_TARGET }}" >> $GITHUB_OUTPUT
          fi
          echo "BUILD_PATH: ${{ env.BUILD_PATH }}"
          echo "BUILD_TARGET: ${{ env.BUILD_TARGET }}"

      - name: Check for lambdas or layers to build
        run: |
          if matrix.lambda == 'None' && matrix.layer == 'None'; then
            echo "No lambdas or layers to build. Exiting."
            exit 0
          fi

      - name: Zip Lambda Layer Code
        if: ${{ env.APP_ENV == 'ndev' }}
        run: |
          cd ${{ env.BUILD_PATH }}
          echo ${{ env.BUILD_PATH }}
          zip -r ${{ env.BUILD_TARGET }}-${{ env.IMAGE_TAG }}.zip . -x ".*"
          if [ ! -f "${{ env.BUILD_TARGET }}-${{ env.IMAGE_TAG }}.zip" ]; then
            echo "Error: Zip file was not created successfully."
            exit 1
          fi
      - name: Upload Build Artifacts to S3
        if: ${{ env.APP_ENV == 'ndev' }}
        run: |
          cd ${{ env.BUILD_PATH }}
          pwd
          # aws s3 cp ${{ env.BUILD_TARGET }}-${{ env.IMAGE_TAG }}.zip s3://${{ vars.ARTIFACTS_BUCKET }}/lambda-builds/${{ env.BUILD_TARGET }}/${{ env.BUILD_TARGET }}-${{ env.IMAGE_TAG }}.zip