name: Build and Release Android App

on:
  push:
    branches:
      - 'dev'
      - 'main'

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Release'
        required: true
        default: 'qa'
        options:
          - qa
          - prod

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          {
            echo "matrix<<EOF"
            
            if [[ ${GITHUB_REF} == 'refs/heads/dev' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
              echo "{\"include\":[{\"release\":\"qa\"}]}"
            elif [[ ${GITHUB_REF} == 'refs/heads/main' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
              echo "{\"include\":[{\"release\":\"prod\"}]}"
            else
              echo ""
            fi
            
            echo EOF
            } >> $GITHUB_OUTPUT
          }
      - name: Print Matrix
        run: |
         echo ${{steps.set-matrix.outputs.matrix}}
