name: Build and Release Android App

on:
  push:
    branches:
      - 'dev'
      - 'main'

  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: 'Release'
        required: true
        default: 'qa'
        options:
          - qa
          - prod

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          {
            echo "matrix<<EOF"

            if [[ ${GITHUB_REF} == 'refs/heads/dev' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
              echo '{"include":[{"release":"qa"}]}'
            elif [[ ${GITHUB_REF} == 'refs/heads/main' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
              echo '{"include":[{"release":"prod"}]}'
            elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
              echo '{"include":[{"release":"${{ github.event.inputs.release }}"}]}'
            else
              echo '{"include":[{"release":"qa"}]}'
            fi

            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Print Matrix
        run: |
         echo ${{steps.set-matrix.outputs.matrix}}

  build:
    needs: [prepare]
    if: ${{ needs.prepare.outputs.matrix != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
      fail-fast: false
    
    steps:
      - name: Print data from prepare for debug
        run: |
          echo ${{ matrix.release }}

      - name: Generate release notes
        id: release_notes
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          COMMIT_HASH=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          COMMIT_AUTHOR=$(git log -1 --pretty='%an <%ae>')
          COMMIT_DATE=$(git log -1 --date=iso --pretty='%cd')
      
          {
            echo "body<<EOF"
            echo "Branch: $BRANCH_NAME"
            echo "Commit: $COMMIT_HASH"
            echo "Message: $COMMIT_MESSAGE"
            echo "Author: $COMMIT_AUTHOR"
            echo "Date: $COMMIT_DATE"
            echo "EOF"
          } >> $GITHUB_OUTPUT


      - name: print release notes
        run: | 
          echo ${{ toJson(steps.release_notes.outputs) }}
      
