name: Set Deployment Matrix

on:
  # push:
  #   branches:
  #     - 'dev'
  #     - 'main'

  pull_request:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'ndev'
        type: choice
        options:
          - ndev
          - nqa
          - stg
          - prod
          - dr
          - preprod
      folder:
        description: 'Select a folder to deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - drivers
          - python-libraries
          - scripts
          - sql-queries

permissions:
  contents: read
  id-token: write
  issues: write
jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}

  #   steps:
  #     - name: Set Matrix
  #       id: set-matrix
  #       run: |
  #         {
  #         # Initialize matrix
  #         if [[ ${GITHUB_REF} == 'refs/heads/dev' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
  #           # Deploy from dev branch to dev
  #           echo "matrix<<EOF"
  #           echo "{\"include\":[{\"env\":\"ndev\"}]}"
  #         elif [[ ${GITHUB_REF} == 'refs/heads/main' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
  #           # Deploy from main branch to prod
  #           echo "matrix<<EOF"
  #           echo "{\"include\":[{\"env\":\"prod\"}]}"
  #         elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
  #           # Workflow dispatch logic
  #           echo "matrix<<EOF"
  #           echo "{\"include\":["
  #               echo "{\"env\":\"${{ github.event.inputs.environment }}\",}"
  #           echo "]}"
  #         else
  #           # Default case: no matrix
  #           echo "matrix<<EOF"
  #           echo ""
  #         fi
  #         echo EOF
  #         } >> $GITHUB_OUTPUT
          
  #     - name: Echo Matrix
  #       run: |
  #         echo "${{ steps.set-matrix.outputs.matrix }}"

  automation-test:
    # if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev' }}
    uses: cardioone/devops-commons/.github/workflows/api-automation.yaml@PLAT-428-Api-Automation-Integration-in-CI-CD
    with:
      service_name: "ms-patient"
      matrix: "{env:ndev,image:1249c9f-dev,build:true},]}"
      service_repo: "cardioone/c1-patientservice"
      # service_repo_branch: ${{ github.head_ref }}
      service_repo_branch: "PLAT-428-Api-Automation-Integration-in-CI-CD"
      automation_branch: "ci-cd"
      auth_username: syed.ali@concertidc.com
      aws_account: 911167887771
      mvn_test_tags: "@PatientServiceApisRegression"
      app_envs: |
        jdbc.username=rhythm
        jdbc.url=jdbc:postgresql://cluster-ndev-rhythm-patient-db.cluster-crisw8w062gc.us-west-2.rds.amazonaws.com/rhythmpatient
        auth.baseurl=https://ms-auth.ndev.rhythm.cardioone.com
        active.config.profile=ndev
        cors.allowed-origins=https://webapp.ndev.rhythm.cardioone.com,http://localhost:3000
        server.port=4000
        APPLICATION_NAME=ms-patient
        config.server.url=https://ms-config.ndev.rhythm.cardioone.com/
        cors.allowed-mappings=/v1/patients/**,/v2/patients/**
        elastic.uris=https://ndev-rhythm.es.us-west-2.aws.found.io
        s3.bucket-name=rhythm-s3-ndev
        s3.region=us-west-2
        redis.host=master.rhythm-cache-replica-grp-ndev.yf8sij.usw2.cache.amazonaws.com
        redis.port=6379
        redis.ssl.enabled=true
        aws.region=us-west-2
        eventbus.name=rhythm-ndev
        ses.from.email=cdxintegration@cardioone.com
        ses.to.emails=DEV_Cdx_Integration_Report@cardioone.com
        emrOrchestrator.baseUrl=https://ms-emrorchestrator.ndev.rhythm.cardioone.com
      env_secrets: |
        {
          "jdbc.password": "aurora/ndev-rhythm-patient-db-rds_password",
          "ringcentral.verificationToken": "ringcentral-ndev-token",
          "bambooLambda.verificationToken": "ndev-bamboo-token",
          "patientProgramCron.verificationToken": "patient_ProgramCron-ndev-token",
          "elastic.apikey": "elastic-ndev-apikey",
          "rhythm.internal.apikey": "rhythm-internal-api-key",
          "smart-meter.apikey": "ndev-smartmeter-credentials",
          "cdx.apikey": "CDx-APIKey"
        }
      
    secrets:
      AUTH_PASSWORD: ""
      TOKEN: "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"
      GH_TOKEN: "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"
      RHYTHM_API_VALUE: ""
      rhythm_client_id: ""

  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Deployment Matrix
        id: set-matrix
        uses: ./.github/set-deployment-matrix
        with:
          environment: ${{ github.event.inputs.environment }}

  set-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set.outputs.environment }}
    steps:
      - name: print git run number
        run: echo ${{ github.run_number }}
      - name: Determine Environment
        id: set
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
            if [[ "$BRANCH" == "dev" ]]; then
              echo "environment=ndev" >> $GITHUB_OUTPUT
            elif [[ "$BRANCH" == "main" ]]; then
              echo "environment=prod" >> $GITHUB_OUTPUT
            else
              echo "Unknown branch: $BRANCH"
              exit 1
            fi
          fi
      - name: print matrix
        run: echo ${{ steps.set.outputs.environment }}
      - name: print
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "gthubref: ${{ github.ref }}"
          
  # approval:
  #   needs: [set-env]
  #   if: |
  #     always() 
  #   runs-on: ubuntu-latest
  #   environment: ${{ needs.set-env.outputs.environment }}
  #   env:
  #     APP_ENV: ${{ needs.set-env.outputs.environment }}
  #   steps:
  #     - name: approve-prod-deployment
  #       if: ${{ env.APP_ENV == 'prod' }}
  #       uses: trstringer/manual-approval@v1
  #       timeout-minutes: 30
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: rperiyasamy
  #         minimum-approvals: 1
  #         issue-title: "Deploying ETL Glue job scripts to ${{ env.APP_ENV }}"

  #     - name: Approval Received
  #       if: ${{ env.APP_ENV == 'prod' }}
  #       run: echo "Approval for deploying ETL Glue job scripts to ${{ env.APP_ENV }} was received"

  #     - name: Auto approve for non-prod environments
  #       if: ${{ env.APP_ENV != 'prod' }}
  #       run: echo "Auto approved for ${{ env.APP_ENV }} environment"
  # approval:
  #   needs: [prepare]
  #   if: |
  #     always() 
  #   strategy:
  #     matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
  #     fail-fast: false
  #   runs-on: ubuntu-latest
  #   environment: ${{ matrix.env }}
  #   env:
  #     APP_ENV: ${{ matrix.env }}
  #   steps:
  #     - name: approve-prod-deployment
  #       if: ${{ matrix.env == 'prod' }}
  #       uses: trstringer/manual-approval@v1
  #       timeout-minutes: 30
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: rperiyasamy
  #         minimum-approvals: 1
  #         issue-title: "Deploying MYAPP to ${{ matrix.env }}"

  #     - name: Approval Received
  #       if: ${{ matrix.env == 'prod' }}
  #       run: echo "Approval for deploying MYAPP to ${{ matrix.env }} was received"

  #     - name: Auto approve for non-prod environments
  #       if: ${{ matrix.env != 'prod' }}
  #       run: echo "Auto approved for ${{ matrix.env }} environment"
        
  build:
    needs: [set-env, set-matrix]
    if: ${{ needs.set-env.outputs.environment }}
    strategy:
      # matrix: ${{ fromJSON(needs.set-env.outputs.environment) }}
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      fail-fast: false
    env:
      FOLDER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.folder || 'all' }}
    runs-on: ubuntu-latest

    steps:
      # - name: print matrix
      #   run: |
      #     echo "ENV => ${{matrix.env}}"
      #     echo ${{matrix}}
      #     echo "FOLDER=> $FOLDER"

      - name: Deploy
        run: |
          echo "Environment: ${{ matrix.env }}"
          echo "Image: ${{ matrix.image }}"
          echo "Build flag: ${{ matrix.build }}"
      
