name: Set Deployment Matrix

on:
  push:
    branches:
      - 'dev'
      - 'main'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'ndev'
        type: choice
        options:
          - ndev
          - nqa
          - stg
          - prod
          - dr
      folder:
        description: 'Select a folder to deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - drivers
          - python-libraries
          - scripts
          - sql-queries

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          {
          # Initialize matrix
          if [[ ${GITHUB_REF} == 'refs/heads/dev' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
            # Deploy from dev branch to dev
            echo "matrix<<EOF"
            echo "{\"include\":[{\"env\":\"ndev\"}]}"
          elif [[ ${GITHUB_REF} == 'refs/heads/main' && ${{ github.event_name }} != 'workflow_dispatch' ]]; then
            # Deploy from main branch to prod
            echo "matrix<<EOF"
            echo "{\"include\":[{\"env\":\"prod\"}]}"
          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            # Workflow dispatch logic
            echo "matrix<<EOF"
            echo "{\"include\":["
                echo "{\"env\":\"${{ github.event.inputs.environment }}\",}"
            echo "]}"
          else
            # Default case: no matrix
            echo "matrix<<EOF"
            echo ""
          fi
          echo EOF
          } >> $GITHUB_OUTPUT
          
      - name: Echo Matrix
        run: |
          echo "${{ steps.set-matrix.outputs.matrix }}"

  build:
    needs: [prepare]
    if: ${{ needs.prepare.outputs.matrix != '' }}
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
      fail-fast: false
    env:
      FOLDER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.folder || 'all' }}
    runs-on: ubuntu-latest

    steps:
      - name: print matrix
        run: |
          echo "ENV => ${{matrix.env}}"
          echo ${{matrix}}
          echo "FOLDER=> ${{ env.FOLDER }}"
