name: WireGuard Setup

on:
  workflow_call:
    inputs:
      ec2_public_ip:
        required: true
        type: string
      ec2_wg_public_key:
        required: true
        type: string

    secrets:
      wireguard_private_key:
        required: true

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard
        run: sudo apt-get update && sudo apt-get install -y wireguard

      - name: Write private key to file
        run: echo "${{ secrets.wireguard_private_key }}" > privatekey

      - name: Configure WireGuard interface
        run: |
          sudo ip link add wg0 type wireguard
          sudo ip address add dev wg0 192.168.2.2 peer 192.168.2.1
          sudo wg set wg0 \
            listen-port 48123 \
            private-key privatekey \
            peer ${{ inputs.ec2_wg_public_key }} \
            allowed-ips 0.0.0.0/0 \
            endpoint ${{ inputs.ec2_public_ip }}:43772
          sudo ip link set up dev wg0

      - name: Add route to VPC
        run: sudo ip route add 172.31.0.0/16 via 192.168.2.1

      - name: Show WireGuard status
        run: sudo wg show

      - name: Show routing table
        run: ip route show

      - name: Show iptables rules
        run: sudo iptables -L
